backend:
  name: github
  repo: Soori74ya/soori74ya.github.io
  branch: main
  base_url: https://sveltia-cms-auth.hwang-soohyun.workers.dev

logo:
  src: ../assets/logo.jpg
  show_in_header: true

i18n:
  structure: single_file
  locales: [ko, en]
  default_locale: ko

app_title: Hwang Soo Hyun

media_folder: /static/assets
public_folder: /assets

media_libraries:
  default:
    config:
      transformations:
        raster_image:
          format: webp
          quality: 90
          width: 1800
          height: 1800
        svg:
          optimize: true

collections:
  - name: work
    label: Work
    folder: /content/work
    create: true
    i18n: true
    media_folder: "{{media_folder}}/work/{{slug}}"
    public_folder: "{{public_folder}}/work/{{slug}}"
    fields:
      - name: title
        label: 제목
        widget: string
        required: true
        i18n: true

      - name: workType
        label: 작업 유형
        widget: string
        required: true
        i18n: duplicate

      - name: startDate
        label: 시작 날짜
        widget: datetime
        type: date
        required: true
        i18n: duplicate

      - name: endDate
        label: 종료 날짜
        widget: datetime
        type: date
        required: false
        i18n: duplicate

      - name: venue
        label: 공연 장소
        widget: string
        required: false
        i18n: true
      
      - name: production
        label: 제작, 주최 및 후원
        widget: text
        required: false
        i18n: true

      - name: credit
        label: 크레딧
        widget: richtext
        required: false
        i18n: true

      - name: description
        label: 작품 내용
        widget: richtext
        required: false
        i18n: true

      - name: articles
        label: 기사
        widget: list
        required: false
        fields:
          - name: title
            label: 제목
            widget: string

          - name: url
            label: 링크
            widget: string

      - name: critics
        label: 비평
        widget: list
        required: false
        fields:
          - name: title
            label: 제목
            widget: string

          - name: url
            label: 링크
            widget: string

      - name: images
        label: 이미지
        widget: file
        multiple: true
        required: false
        
  
  - name: biography
    label: Biography
    files:
      - name: biography
        label: Biography
        file: content/biography.md
        fields:
          - name: bio_kr
            label: 국문 소개
            widget: richtext

          - name: bio_en
            label: 영문 소개
            widget: richtext
          
          - name: experience
            label: 경력
            widget: list
            fields:
              - { name: year, label: 년도, widget: string }
              - { name: description_ko, label: 국문 내용, widget: string }
              - { name: description_en, label: 영문 내용, widget: string }

          - name: awards
            label: 수상
            widget: list
            fields:
              - { name: year, label: 년도, widget: string }
              - { name: description_kr, label: 국문 내용, widget: string }
              - { name: description_en, label: 영문 내용, widget: string }
              
          - name: residencies
            label: 레지던시
            widget: list
            fields:
              - { name: year, label: 년도, widget: string }
              - { name: description_kr, label: 국문 내용, widget: string }
              - { name: description_en, label: 영문 내용, widget: string }

          - name: education_workshops
            label: 교육 및 워크숍
            widget: list
            fields:
              - { name: year, label: 년도, widget: string }
              - { name: description_kr, label: 국문 내용, widget: string }
              - { name: description_en, label: 영문 내용, widget: string }
              
          - name: choreography
            label: 안무작
            widget: list
            fields:
              - { name: year, label: 년도, widget: string }
              - { name: description_kr, label: 국문 내용, widget: string }
              - { name: description_en, label: 영문 내용, widget: string }
              
          - name: collaborations
            label: 협업 및 협력 프로젝트
            widget: list
            fields:
              - { name: year, label: 년도, widget: string }
              - { name: description_kr, label: 국문 내용, widget: string }
              - { name: description_en, label: 영문 내용, widget: string }
              
          - name: performances
            label: 출연작
            widget: list
            fields:
              - { name: year, label: 년도, widget: string }
              - { name: description_kr, label: 국문 내용, widget: string }
              - { name: description_en, label: 영문 내용, widget: string }
              
  - name: news
    label: News
    files:
      - name: news
        label: News
        file: content/news.md
        fields:
          - name: news
            label: 뉴스 목록
            widget: list
            fields:
              - name: start_date
                label: 시작 날짜
                widget: datetime
                format: YYYY-MM-DD
                required: true

              - name: end_date
                label: 종료 날짜
                widget: datetime
                format: YYYY-MM-DD
                required: false

              - name: title
                label: 제목
                widget: string
                required: true

              - name: venue
                label: 장소
                widget: string
                required: false

              - name: link
                label: 링크
                widget: string
                required: false